### ISSUE TITLE
Different Spatial References as Parameter

### ISSUE THREAD

**Issue by DenisCarriere** [lokku/opencagedata-roadmap#3]
Would it be possible to add different Spatial References outputs to your Geocoder (EPSG: 4326 WGS84 & 3857 Spherical Mercator)

I'm asking for this because someone might be using a mapping platform that would require coordinates in Meters instead of Degrees, by doing this you would reproject the data using some kind of GDAL[http://gdal.org] transformation on the server side so that when it hits the client he would have the correct projection without doing much extra work.

Offering a few standard projects that are available with the GDAL library would be enough to handle that apetite.

By default the spatial reference should be WGS84 (epsg:4326), but it's always nice to have that flexiblity to change it.

**URL Request example**
`http://api.opencagedata.com/geocode/v1/json?q=PLACENAME&key=YOURKEY&epsg=4326`

**Comment by freyfogle** [comment]
We'll probably do this as an annotation, similarly to how we do the OSGB annotation for Ordnance Survey gridrefs
http://geocoder.opencagedata.com/api.html#annotations

**Comment by DenisCarriere** [comment]
That's a good idea

**Comment by freyfogle** [comment]
This just went live, there is now an annotation called "Mercator", will blog about it this afternoon. Enjoy, all feedback welcome. and please keep the ideas coming

**Comment by DenisCarriere** [comment]
Awesome work Ed, I'll be looking forward in seeing it

**Comment by freyfogle** [comment]
Blog post is now up 
http://blog.opencagedata.com/post/108163937808/three-new-annotations-mercator-dms-itm

**Comment by DenisCarriere** [comment]
The link does not seem to work, I don't know if it's just my internet connection or if the link is broken.

**Comment by mtmail** [comment]
works fine for me (I'm in a different country from Ed)
http://downforeveryoneorjustme.com/http://blog.opencagedata.com/post/108163937808/three-new-annotations-mercator-dms-itm

**Comment by DenisCarriere** [comment]
Ok, might be just my work computer, I'll try out the link when I'm at home.

Cheers,
